class PyIdentityModelException(Exception):
    """Raised due to an issue with the token verification process"""


__all__ = ["PyIdentityModelException"]
